name: RT
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run_application_mac:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3
      - run: make

  run_application_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make
      